// Permitted because `tdx_get_report0` (generated by `nix::ioctl_readwrite!`)
// is an `unsafe fn`. Every `unsafe` block here is annotated with a SAFETY
// comment explaining why the invariants hold.
#![allow(unsafe_code)]

//! VsockQuoter — TDX quote generation via the vsock-direct QGS path.
//!
//! Why not the kernel TSM path?  The upstream Linux `drivers/virt/coco/tdx-guest`
//! TSM driver implements `wait_for_quote_completion()` with a hard-coded
//! `msleep_interruptible(MSEC_PER_SEC)` loop. Quote generation completes in
//! ~50–150 ms in hardware, but the driver only wakes up to *check* the
//! completion flag once per second, so every `outblob` read takes ~1024 ms
//! end-to-end. This is purely a kernel implementation choice — it is not
//! mandated by the TDX architecture (see Intel TDX DCAP Quote Library API
//! spec, IETF draft-fossati-tls-attestation-09, Canonical Ubuntu TDX docs).
//!
//! The Intel-recommended attestation path (libtdx-attest, R3AAL) bypasses
//! the kernel quote helper entirely:
//!
//!   1. `ioctl(/dev/tdx_guest, TDX_CMD_GET_REPORT0, &req)` — pure SEAMCALL,
//!      sub-millisecond, returns a 1024-byte TDREPORT bound to our 64-byte
//!      report_data.
//!   2. Open an AF_VSOCK socket to (CID=2, port=4050) — that's the host's
//!      QGS listener (qgsd from the Canonical PPA, configured in QEMU as
//!      `quote-generation-socket {type:"vsock", cid:"2", port:"4050"}`).
//!   3. Wrap the TDREPORT in a QGS protocol message and send it; QGS
//!      forwards to the Quoting Enclave on the host, gets a TDX-DCAP
//!      ECDSA-P384 signed quote, and returns it.
//!
//! The QGS wire protocol is documented in Intel SGXDataCenterAttestationPrimitives
//! `qgs_msg_lib.h` (`qgs_msg_get_quote_req_t` and `qgs_msg_get_quote_resp_t`).
//! Empirically (cctrusted_vm probe on this host) the round-trip is 2.6–6.1 ms,
//! ~270× faster than the configfs-tsm path on stock Linux.
//!
//! This module preserves the same `QuoteProvider` contract as `TsmQuoter`,
//! so `trustd::service::build_attest_bundle` and the unix-RPC call sites
//! don't change. Workload-id binding, report_data canonicalization
//! (`SHA384(nonce)[..32] || SHA384(peer_pk)[..32]`), and event-log
//! bundling all stay inside trustd — only the quote backend swaps.

use std::io::{Read, Write};
use std::path::Path;
use std::sync::Mutex;
use std::time::Duration;

use byteorder::{BigEndian, LittleEndian, ReadBytesExt, WriteBytesExt};
use nix::ioctl_readwrite;

use crate::error::{AgentError, Result};
use crate::tdquote::QuoteProvider;

// ─────────────────────────────────────────────────────────────────────────────
// /dev/tdx_guest TDREPORT ioctl
// ─────────────────────────────────────────────────────────────────────────────

/// Path to the TDX guest character device exposed by the upstream kernel.
/// Owned by user `root`, group `tdx_guest`, perms 0660 on Canonical Ubuntu.
pub const TDX_GUEST_DEVICE: &str = "/dev/tdx_guest";

/// 64-byte caller-supplied input data — usually
/// `SHA384(nonce)[..32] || SHA384(peer_pk)[..32]` per
/// the TrustMCP report_data canonicalisation rule.
pub const REPORTDATA_SIZE: usize = 64;

/// 1024-byte TDREPORT_STRUCT returned by TDX 1.5 hardware.
pub const TDREPORT_SIZE: usize = 1024;

/// Layout of the `tdx_report_req` struct in the upstream kernel
/// (`include/uapi/linux/tdx-guest.h`). Field order and `#[repr(C)]` are
/// load-bearing: the kernel reads these offsets directly.
#[repr(C)]
#[derive(Clone, Copy)]
struct TdxReportReq {
    reportdata: [u8; REPORTDATA_SIZE],
    tdreport: [u8; TDREPORT_SIZE],
}

// TDX_CMD_GET_REPORT0 — type 'T', nr 1, IOC_RW, sizeof(TdxReportReq) = 1088.
// Matches the magic and number used by the upstream tdx-guest driver.
ioctl_readwrite!(tdx_get_report0, b'T', 1, TdxReportReq);

fn fetch_tdreport(report_data: &[u8]) -> Result<[u8; TDREPORT_SIZE]> {
    if report_data.len() != REPORTDATA_SIZE {
        return Err(AgentError::InvalidInput(format!(
            "report_data must be {REPORTDATA_SIZE} bytes, got {}",
            report_data.len()
        )));
    }

    use std::os::fd::AsRawFd;
    let dev = std::fs::OpenOptions::new()
        .read(true)
        .write(true)
        .open(TDX_GUEST_DEVICE)
        .map_err(|source| AgentError::io(TDX_GUEST_DEVICE, source))?;

    let mut req = TdxReportReq {
        reportdata: [0u8; REPORTDATA_SIZE],
        tdreport: [0u8; TDREPORT_SIZE],
    };
    req.reportdata.copy_from_slice(report_data);

    // SAFETY: `req` is a properly-initialised `#[repr(C)]` struct of the
    // exact size and layout the kernel expects for TDX_CMD_GET_REPORT0.
    // `dev.as_raw_fd()` is valid for the duration of this call.
    unsafe {
        tdx_get_report0(dev.as_raw_fd(), &mut req).map_err(|errno| {
            AgentError::Internal(format!(
                "TDX_CMD_GET_REPORT0 ioctl failed: {errno}"
            ))
        })?;
    }
    Ok(req.tdreport)
}

// ─────────────────────────────────────────────────────────────────────────────
// QGS wire protocol
// ─────────────────────────────────────────────────────────────────────────────
//
// On-wire framing for both directions: one 4-byte big-endian length prefix,
// followed by `length` bytes of QGS message body.
//
// Body layout (little-endian, native x86 ordering as in qgs_msg_lib.h):
//
//   qgs_msg_header_t {
//       u16 major_version;        // 1
//       u16 minor_version;        // 0
//       u32 type;                 // 0 = GET_QUOTE_REQ, 1 = GET_QUOTE_RESP
//       u32 size;                 // total body bytes including header
//       u32 error_code;           // request: 0; response: 0 = success
//   }
//   qgs_msg_get_quote_req_t / _resp_t {
//       u32 report_size or selected_id_size;
//       u32 id_list_size or quote_size;
//       u8  body[...];   // request: TDREPORT bytes; response: id || quote
//   }

const QGS_MSG_HEADER_BYTES: usize = 16; // 2H 3I
const QGS_MSG_QUOTE_REQ_PREAMBLE: usize = 8; // 2I after header
const QGS_TYPE_GET_QUOTE_REQ: u32 = 0;
const QGS_TYPE_GET_QUOTE_RESP: u32 = 1;

/// Default CID for the host on AF_VSOCK; matches `VMADDR_CID_HOST` in <linux/vm_sockets.h>.
pub const DEFAULT_QGS_VSOCK_CID: u32 = 2;
/// Default QGS listener port on Canonical Ubuntu TDX hosts.
pub const DEFAULT_QGS_VSOCK_PORT: u32 = 4050;
/// Tight upper bound — TDX QGS round-trip is single-digit ms in steady state;
/// allow a few seconds of headroom for first-call PCK fetches inside QGS.
const VSOCK_RW_TIMEOUT: Duration = Duration::from_secs(30);

fn build_quote_request(tdreport: &[u8; TDREPORT_SIZE]) -> Result<Vec<u8>> {
    let report_size = tdreport.len() as u32;
    let body_size: u32 =
        (QGS_MSG_HEADER_BYTES + QGS_MSG_QUOTE_REQ_PREAMBLE) as u32 + report_size;
    let mut buf: Vec<u8> = Vec::with_capacity(body_size as usize);
    // header
    buf.write_u16::<LittleEndian>(1).unwrap(); // major_version
    buf.write_u16::<LittleEndian>(0).unwrap(); // minor_version
    buf.write_u32::<LittleEndian>(QGS_TYPE_GET_QUOTE_REQ).unwrap();
    buf.write_u32::<LittleEndian>(body_size).unwrap();
    buf.write_u32::<LittleEndian>(0).unwrap(); // error_code
    // get_quote_req body
    buf.write_u32::<LittleEndian>(report_size).unwrap();
    buf.write_u32::<LittleEndian>(0).unwrap(); // id_list_size
    buf.extend_from_slice(tdreport);
    Ok(buf)
}

fn parse_quote_response(resp: &[u8]) -> Result<Vec<u8>> {
    let min_len = QGS_MSG_HEADER_BYTES + QGS_MSG_QUOTE_REQ_PREAMBLE;
    if resp.len() < min_len {
        return Err(AgentError::Parse(format!(
            "QGS response too short: {} < {min_len}",
            resp.len()
        )));
    }
    let mut cur = std::io::Cursor::new(resp);
    let _major = cur.read_u16::<LittleEndian>().unwrap();
    let _minor = cur.read_u16::<LittleEndian>().unwrap();
    let msg_type = cur.read_u32::<LittleEndian>().unwrap();
    let _size = cur.read_u32::<LittleEndian>().unwrap();
    let error_code = cur.read_u32::<LittleEndian>().unwrap();
    if msg_type != QGS_TYPE_GET_QUOTE_RESP {
        return Err(AgentError::Parse(format!(
            "QGS unexpected msg type: {msg_type}"
        )));
    }
    if error_code != 0 {
        return Err(AgentError::Unavailable(format!(
            "QGS returned error_code={error_code}"
        )));
    }
    let _selected_id_size = cur.read_u32::<LittleEndian>().unwrap();
    let quote_size = cur.read_u32::<LittleEndian>().unwrap() as usize;
    let pos = cur.position() as usize;
    let end = pos
        .checked_add(quote_size)
        .ok_or_else(|| AgentError::Parse("QGS quote_size overflow".into()))?;
    if end > resp.len() {
        return Err(AgentError::Parse(format!(
            "QGS truncated quote: declared {quote_size}, available {}",
            resp.len() - pos
        )));
    }
    Ok(resp[pos..end].to_vec())
}

// ─────────────────────────────────────────────────────────────────────────────
// Public type
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug)]
pub struct VsockQuoter {
    qgs_cid: u32,
    qgs_port: u32,
    /// Some QGS implementations are single-threaded server-side; we serialise
    /// here so multiple concurrent attest_workload callers don't trip on each
    /// other's responses or saturate the daemon's accept queue.
    lock: Mutex<()>,
}

impl VsockQuoter {
    pub fn new(qgs_cid: u32, qgs_port: u32) -> Self {
        Self {
            qgs_cid,
            qgs_port,
            lock: Mutex::new(()),
        }
    }
}

impl Default for VsockQuoter {
    fn default() -> Self {
        Self::new(DEFAULT_QGS_VSOCK_CID, DEFAULT_QGS_VSOCK_PORT)
    }
}

impl QuoteProvider for VsockQuoter {
    fn available(&self) -> bool {
        // We need both the TDREPORT ioctl device and a reachable QGS. The
        // device check is cheap; the QGS reachability check is deferred to
        // the first get_quote call so we don't pay a connect()+close() on
        // every health probe.
        Path::new(TDX_GUEST_DEVICE).exists()
    }

    fn get_quote(&self, report_data: &[u8]) -> Result<Vec<u8>> {
        let _guard = self
            .lock
            .lock()
            .map_err(|_| AgentError::Internal("vsock quote lock poisoned".to_owned()))?;

        let tdreport = fetch_tdreport(report_data)?;
        let req_body = build_quote_request(&tdreport)?;

        // Connect AF_VSOCK to (qgs_cid, qgs_port). On Ubuntu TDX the QGS
        // daemon (qgsd) listens at (CID=2, port=4050).
        let addr = vsock::VsockAddr::new(self.qgs_cid, self.qgs_port);
        let mut sock = vsock::VsockStream::connect(&addr).map_err(|e| {
            AgentError::Unavailable(format!(
                "vsock connect to ({}, {}) failed: {e}",
                self.qgs_cid, self.qgs_port
            ))
        })?;

        sock.set_read_timeout(Some(VSOCK_RW_TIMEOUT))
            .map_err(|e| AgentError::Internal(format!("vsock set_read_timeout: {e}")))?;
        sock.set_write_timeout(Some(VSOCK_RW_TIMEOUT))
            .map_err(|e| AgentError::Internal(format!("vsock set_write_timeout: {e}")))?;

        // Write big-endian length prefix + body
        sock.write_u32::<BigEndian>(req_body.len() as u32)
            .map_err(|e| AgentError::Internal(format!("vsock write len: {e}")))?;
        sock.write_all(&req_body)
            .map_err(|e| AgentError::Internal(format!("vsock write body: {e}")))?;

        // Read big-endian length prefix + body
        let resp_len = sock
            .read_u32::<BigEndian>()
            .map_err(|e| AgentError::Internal(format!("vsock read len: {e}")))?
            as usize;
        // Sanity bound — TDX quotes are ~5 KiB; cap at 64 KiB to avoid
        // an attacker-controlled allocation if the wire is malformed.
        const MAX_QGS_RESP: usize = 64 * 1024;
        if resp_len == 0 || resp_len > MAX_QGS_RESP {
            return Err(AgentError::Parse(format!(
                "QGS response length out of bounds: {resp_len}"
            )));
        }
        let mut resp = vec![0u8; resp_len];
        sock.read_exact(&mut resp)
            .map_err(|e| AgentError::Internal(format!("vsock read body: {e}")))?;

        let quote = parse_quote_response(&resp)?;
        if quote.is_empty() {
            return Err(AgentError::Unavailable(
                "QGS returned empty quote".to_owned(),
            ));
        }
        Ok(quote)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn build_request_size_and_header() {
        let tdr = [0xCAu8; TDREPORT_SIZE];
        let buf = build_quote_request(&tdr).unwrap();
        // header (16) + req-preamble (8) + tdreport (1024) = 1048
        assert_eq!(buf.len(), QGS_MSG_HEADER_BYTES + QGS_MSG_QUOTE_REQ_PREAMBLE + TDREPORT_SIZE);
        // major=1, minor=0
        assert_eq!(u16::from_le_bytes([buf[0], buf[1]]), 1);
        assert_eq!(u16::from_le_bytes([buf[2], buf[3]]), 0);
        // type = GET_QUOTE_REQ = 0
        assert_eq!(u32::from_le_bytes([buf[4], buf[5], buf[6], buf[7]]), 0);
        // size = full body length
        assert_eq!(
            u32::from_le_bytes([buf[8], buf[9], buf[10], buf[11]]) as usize,
            buf.len()
        );
        // tdreport bytes start at offset 24 (header 16 + preamble 8)
        assert_eq!(buf[24], 0xCA);
        assert_eq!(buf[buf.len() - 1], 0xCA);
    }

    #[test]
    fn parse_response_extracts_quote() {
        // Build a synthetic GET_QUOTE_RESP carrying a 5-byte "quote".
        let mut resp = Vec::new();
        resp.write_u16::<LittleEndian>(1).unwrap(); // major
        resp.write_u16::<LittleEndian>(0).unwrap(); // minor
        resp.write_u32::<LittleEndian>(QGS_TYPE_GET_QUOTE_RESP).unwrap();
        resp.write_u32::<LittleEndian>(0).unwrap(); // size (unused)
        resp.write_u32::<LittleEndian>(0).unwrap(); // error_code = success
        resp.write_u32::<LittleEndian>(0).unwrap(); // selected_id_size
        resp.write_u32::<LittleEndian>(5).unwrap(); // quote_size
        resp.extend_from_slice(b"hello");
        let q = parse_quote_response(&resp).unwrap();
        assert_eq!(q, b"hello");
    }

    #[test]
    fn parse_response_rejects_error_code() {
        let mut resp = Vec::new();
        resp.write_u16::<LittleEndian>(1).unwrap();
        resp.write_u16::<LittleEndian>(0).unwrap();
        resp.write_u32::<LittleEndian>(QGS_TYPE_GET_QUOTE_RESP).unwrap();
        resp.write_u32::<LittleEndian>(0).unwrap();
        resp.write_u32::<LittleEndian>(0xdead_beef).unwrap(); // error
        resp.write_u32::<LittleEndian>(0).unwrap();
        resp.write_u32::<LittleEndian>(0).unwrap();
        let err = parse_quote_response(&resp).unwrap_err();
        assert!(format!("{err}").contains("error_code=3735928559"));
    }

    #[test]
    fn parse_response_rejects_wrong_type() {
        let mut resp = Vec::new();
        resp.write_u16::<LittleEndian>(1).unwrap();
        resp.write_u16::<LittleEndian>(0).unwrap();
        resp.write_u32::<LittleEndian>(QGS_TYPE_GET_QUOTE_REQ).unwrap(); // wrong
        resp.write_u32::<LittleEndian>(0).unwrap();
        resp.write_u32::<LittleEndian>(0).unwrap();
        resp.write_u32::<LittleEndian>(0).unwrap();
        resp.write_u32::<LittleEndian>(0).unwrap();
        let err = parse_quote_response(&resp).unwrap_err();
        assert!(format!("{err}").contains("unexpected msg type"));
    }

    #[test]
    fn report_data_length_is_validated() {
        let q = VsockQuoter::default();
        let err = q.get_quote(&[0u8; 63]).unwrap_err();
        assert!(format!("{err}").contains("64 bytes"));
    }
}
